export interface ProviderCatalogEntry {
  name: string;
  slug: string;
  country: string;
  service: string;
}

export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [

  { name: "Deel", slug: "deel", country: "Global", service: "EOR" },
  { name: "Remote", slug: "remote", country: "Global", service: "EOR" },
  { name: "Oyster", slug: "oyster", country: "Global", service: "EOR" },
  { name: "Rippling", slug: "rippling", country: "Global", service: "HRIS" },
  { name: "Atlas", slug: "atlas", country: "Global", service: "EOR" },
  { name: "Papaya Global", slug: "papaya-global", country: "Global", service: "Payroll" },
  { name: "Velocity Global", slug: "velocity-global", country: "Global", service: "EOR" },
  { name: "Multiplier", slug: "multiplier", country: "Global", service: "EOR" },
  { name: "Globalization Partners", slug: "globalization-partners", country: "Global", service: "EOR" },
  { name: "Safeguard Global", slug: "safeguard-global", country: "Global", service: "Incorporation" },
  { name: "Omnipresent", slug: "omnipresent", country: "Global", service: "EOR" },
  { name: "Skuad", slug: "skuad", country: "Global", service: "Payroll" },
  { name: "Horizons", slug: "horizons", country: "Global", service: "EOR" },
  { name: "WorkMotion", slug: "workmotion", country: "Global", service: "EOR" },
  { name: "Plane", slug: "plane", country: "Global", service: "Global Payments" },
  { name: "Remofirst", slug: "remofirst", country: "Global", service: "EOR" },
  { name: "Boundless", slug: "boundless", country: "Global", service: "Payroll" },
  { name: "Envoy Global", slug: "envoy-global", country: "Global", service: "Immigration" },
  { name: "Fragomen", slug: "fragomen", country: "Global", service: "Immigration" },
  { name: "Localyze", slug: "localyze", country: "Global", service: "HRIS" },
  { name: "Jobbatical", slug: "jobbatical", country: "Global", service: "Immigration" },
  { name: "Topia", slug: "topia", country: "Global", service: "Immigration" },
  { name: "Graebel", slug: "graebel", country: "Global", service: "Software" },
  { name: "Crown World Mobility", slug: "crown-world-mobility", country: "Global", service: "Relocation" },
  { name: "Santa Fe Relocation", slug: "santa-fe-relocation", country: "Global", service: "Relocation" },
  { name: "Greenhouse", slug: "greenhouse", country: "Global", service: "Staffing" },
  { name: "Lever", slug: "lever", country: "Global", service: "Staffing" },
  { name: "Ashby", slug: "ashby", country: "Global", service: "Staffing" },
  { name: "Recruitee", slug: "recruitee", country: "Global", service: "Staffing" },
  { name: "SmartRecruiters", slug: "smartrecruiters", country: "Global", service: "Staffing" },
  { name: "Jobvite", slug: "jobvite", country: "Global", service: "Staffing" },
  { name: "iCIMS", slug: "icims", country: "Global", service: "Staffing" },
  { name: "Workable", slug: "workable", country: "Global", service: "Staffing" },
  { name: "Upwork", slug: "upwork", country: "Global", service: "Contractor Management" },
  { name: "Toptal", slug: "toptal", country: "Global", service: "Staffing" },
  { name: "Fiverr", slug: "fiverr", country: "Global", service: "Contractor Management" },
  { name: "Contra", slug: "contra", country: "Global", service: "Contractor Management" },
  { name: "Braintrust", slug: "braintrust", country: "Global", service: "Staffing" },
  { name: "Malt", slug: "malt", country: "Global", service: "Contractor Management" },
  { name: "Gigster", slug: "gigster", country: "Global", service: "Software" },
  { name: "A.Team", slug: "a.team", country: "Global", service: "Staffing" },
  { name: "PayPal", slug: "paypal", country: "Global", service: "Global Payments" },
  { name: "Checkout.com", slug: "checkout.com", country: "Global", service: "Global Payments" },
  { name: "Rapyd", slug: "rapyd", country: "Global", service: "Global Payments" },
  { name: "Nium", slug: "nium", country: "Global", service: "Global Payments" },
  { name: "Currencycloud", slug: "currencycloud", country: "Global", service: "Global Payments" },
  { name: "Payone", slug: "payone", country: "Global", service: "Global Payments" },
  { name: "Thunes", slug: "thunes", country: "Global", service: "Global Payments" },
  { name: "QuickBooks", slug: "quickbooks", country: "Global", service: "Accounting" },
  { name: "Xero", slug: "xero", country: "Global", service: "Accounting" },
  { name: "FreshBooks", slug: "freshbooks", country: "Global", service: "Accounting" },
  { name: "Bench", slug: "bench", country: "Global", service: "Accounting" },
  { name: "Pilot", slug: "pilot", country: "Global", service: "Accounting" },
  { name: "Avalara", slug: "avalara", country: "Global", service: "Tax" },
  { name: "TaxJar", slug: "taxjar", country: "Global", service: "Tax" },
  { name: "Mercury", slug: "mercury", country: "Global", service: "Banking" },
  { name: "Brex", slug: "brex", country: "Global", service: "Banking" },
  { name: "Revolut Business", slug: "revolut-business", country: "Global", service: "Banking" },
  { name: "Qonto", slug: "qonto", country: "Global", service: "Banking" },
  { name: "Relay", slug: "relay", country: "Global", service: "Banking" },
  { name: "Bluevine", slug: "bluevine", country: "Global", service: "Banking" },
  { name: "Stripe Atlas", slug: "stripe-atlas", country: "Global", service: "undefined" },
  { name: "Doola", slug: "doola", country: "Global", service: "Incorporation" },
  { name: "Clerky", slug: "clerky", country: "Global", service: "Incorporation" },
  { name: "LegalZoom", slug: "legalzoom", country: "Global", service: "Compliance,Legal Services" },
  { name: "ZenBusiness", slug: "zenbusiness", country: "Global", service: "Incorporation" },
  { name: "Carta", slug: "carta", country: "Global", service: "HRIS" },
  { name: "Pulley", slug: "pulley", country: "Global", service: "HRIS" },
  { name: "AngelList", slug: "angellist", country: "Global", service: "Staffing" },
  { name: "Ledgy", slug: "ledgy", country: "Global", service: "HRIS" },
  { name: "Cake Equity", slug: "cake-equity", country: "Global", service: "HRIS" },
  { name: "Shareworks", slug: "shareworks", country: "Global", service: "HRIS" },
  { name: "SafetyWing", slug: "safetywing", country: "Global", service: "Benefits" },
  { name: "Remote Health", slug: "remote-health", country: "Global", service: "Benefits" },
  { name: "Allianz Global Benefits", slug: "allianz-global-benefits", country: "Global", service: "Benefits" },
  { name: "Mercer", slug: "mercer", country: "Global", service: "Benefits" },
  { name: "Alight Solutions", slug: "alight-solutions", country: "Global", service: "Benefits" },
  { name: "Plum", slug: "plum", country: "Global", service: "Benefits" },
  { name: "Checkr", slug: "checkr", country: "Global", service: "Compliance" },
  { name: "HireRight", slug: "hireright", country: "Global", service: "Compliance" },
  { name: "Sterling", slug: "sterling", country: "Global", service: "Compliance" },
  { name: "Onfido", slug: "onfido", country: "Global", service: "Compliance" },
  { name: "Persona", slug: "persona", country: "Global", service: "Compliance" },
  { name: "Trulioo", slug: "trulioo", country: "Global", service: "Compliance" },
  { name: "Hubstaff", slug: "hubstaff", country: "Global", service: "Software" },
  { name: "Time Doctor", slug: "time-doctor", country: "Global", service: "Software" },
  { name: "Clockify", slug: "clockify", country: "Global", service: "Software" },
  { name: "Toggl", slug: "toggl", country: "Global", service: "Software" },
  { name: "Harvest", slug: "harvest", country: "Global", service: "Software" },
  { name: "RescueTime", slug: "rescuetime", country: "Global", service: "Software" },
  { name: "Ramp", slug: "ramp", country: "Global", service: "Banking" },
  { name: "Expensify", slug: "expensify", country: "Global", service: "Accounting" },
  { name: "Spendesk", slug: "spendesk", country: "Global", service: "Accounting" },
  { name: "Divvy", slug: "divvy", country: "Global", service: "Banking" },
  { name: "Airbase", slug: "airbase", country: "Global", service: "Accounting" },
  { name: "Pleo", slug: "pleo", country: "Global", service: "Accounting" },
  { name: "Visier", slug: "visier", country: "Global", service: "HRIS" },
  { name: "ChartHop", slug: "charthop", country: "Global", service: "HRIS" },
  { name: "Crunchr", slug: "crunchr", country: "Global", service: "HRIS" },
  { name: "One Model", slug: "one-model", country: "Global", service: "HRIS" },
  { name: "SplashBI", slug: "splashbi", country: "Global", service: "HRIS" },
  { name: "OrgVue", slug: "orgvue", country: "Global", service: "Software" },
  { name: "Gloroots", slug: "gloroots", country: "India", service: "EOR" },
  { name: "Playroll", slug: "playroll", country: "Global", service: "Payroll" },
  { name: "Native Teams", slug: "native-teams", country: "Global", service: "EOR" },
  { name: "CloudPay", slug: "cloudpay", country: "Global", service: "Payroll" },
  { name: "TMF Group", slug: "tmf-group", country: "Global", service: "Incorporation" },
  { name: "Vistra", slug: "vistra", country: "Global", service: "Incorporation" },
  { name: "HSP Group", slug: "hsp-group", country: "Global", service: "Incorporation" },
  { name: "Lano", slug: "lano", country: "Global", service: "Payroll" },
  { name: "GoGlobal", slug: "goglobal", country: "Global", service: "EOR" },
  { name: "Justworks", slug: "justworks", country: "United States", service: "EOR" },
  { name: "TriNet", slug: "trinet", country: "United States", service: "EOR" },
  { name: "Insperity", slug: "insperity", country: "United States", service: "EOR" },
  { name: "Vakilsearch", slug: "vakilsearch", country: "India", service: "Incorporation" },
  { name: "Booth & Partners", slug: "booth-and-partners", country: "Philippines", service: "Staffing" },
  { name: "ANSR", slug: "ansr", country: "India", service: "Staffing" },
  { name: "Abillio", slug: "abillio", country: "Global", service: "Contractor Management" },
  { name: "Ruul", slug: "ruul", country: "Global", service: "Contractor Management" },
  { name: "indinero", slug: "indinero", country: "United States", service: "Accounting" },
  { name: "CoCountant", slug: "cocountant", country: "United States", service: "Accounting" },
  { name: "1-800Accountant", slug: "1800accountant", country: "United States", service: "Accounting" },
  { name: "Avenues Financial", slug: "avenues-financial", country: "United States", service: "Accounting" },
  { name: "Zenbooks", slug: "zenbooks", country: "Canada", service: "Accounting" },
  { name: "MaxSource Private Ltd", slug: "maxsource", country: "India", service: "EOR" },
  { name: "Wisemonk", slug: "wisemonk", country: "India", service: "EOR" },
  { name: "INS Global", slug: "ins-global", country: "Global", service: "EOR" },
  { name: "TopSource Worldwide", slug: "topsource-worldwide", country: "Global", service: "EOR" },
  { name: "Slasify", slug: "slasify", country: "Global", service: "Payroll" },
  { name: "Accenture Song", slug: "accenture-song", country: "Global", service: "Marketing" },
  { name: "Wieden+Kennedy", slug: "wieden-kennedy", country: "Global", service: "Marketing" },
  { name: "Ogilvy", slug: "ogilvy", country: "Global", service: "Marketing" },
  { name: "Hearts & Science", slug: "hearts-science", country: "Global", service: "Marketing" },
  { name: "TEAM LEWIS", slug: "team-lewis", country: "Global", service: "Marketing" },
  { name: "NoGood", slug: "nogood", country: "Global", service: "Marketing" },
  { name: "Digitas", slug: "digitas", country: "Global", service: "Marketing" },
  { name: "FINN Partners", slug: "finn-partners", country: "Global", service: "Marketing" },
  { name: "Jung von Matt", slug: "jung-von-matt", country: "Global", service: "Marketing" },
  { name: "Mother", slug: "mother", country: "Global", service: "Marketing" },
  { name: "84.Paris", slug: "84-paris", country: "Global", service: "Marketing" },
  { name: "UNRVLD", slug: "unrvld", country: "Global", service: "Marketing" },
  { name: "Earnest", slug: "earnest", country: "Global", service: "Marketing" },
  { name: "Delante", slug: "delante", country: "Global", service: "Marketing" },
  { name: "Netpeak", slug: "netpeak", country: "Global", service: "Marketing" },
  { name: "Beyond Borders Marketing", slug: "beyond-borders-marketing", country: "Global", service: "Marketing" },
  { name: "Ironpaper", slug: "ironpaper", country: "Global", service: "Marketing" },
  { name: "Walker Sands", slug: "walkersands", country: "Global", service: "Marketing" },
  { name: "SmartBug Media", slug: "smartbug-media", country: "Global", service: "Marketing" },
  { name: "Velocity Partners", slug: "velocity-partners", country: "Global", service: "Marketing" },
  { name: "Gravity Global", slug: "gravity-global", country: "Global", service: "Marketing" },
  { name: "MarketBridge", slug: "marketbridge", country: "Global", service: "Marketing" },
  { name: "Directive Consulting", slug: "directive-consulting", country: "Global", service: "Marketing" },
  { name: "Siege Media", slug: "siege-media", country: "Global", service: "Marketing" },
  { name: "Power Digital", slug: "power-digital", country: "Global", service: "Marketing" },
  { name: "Global People Strategist", slug: "global-people-strategist", country: "Global", service: "Payroll" },
  { name: "Slash", slug: "slash", country: "Global", service: "Banking" },
  { name: "Kanzum", slug: "kanzum", country: "Global", service: "Banking" },
  { name: "Airwallex", slug: "airwallex", country: "Global", service: "Banking" },
  { name: "Boundless Immigration", slug: "boundless-immigration", country: "Global", service: "Immigration" },
  { name: "Juro", slug: "juro", country: "Global", service: "Contractor Management" },
  { name: "Ironclad", slug: "ironclad", country: "Global", service: "Contractor Management" },
  { name: "Icertis", slug: "icertis", country: "Global", service: "Contractor Management" },
  { name: "Sap Fieldglass", slug: "sap-fieldglass", country: "Global", service: "Contractor Management" },
  { name: "Beeline", slug: "beeline", country: "Global", service: "Contractor Management" },
  { name: "Workday Vndly", slug: "workday-vndly", country: "Global", service: "Contractor Management" },
  { name: "Mbo Partners", slug: "mbo-partners", country: "Global", service: "Contractor Management" },
  { name: "Talentdesk.io", slug: "talentdesk-io", country: "Global", service: "Contractor Management" },
  { name: "Yunojuno", slug: "yunojuno", country: "Global", service: "Contractor Management" },
  { name: "Worksome", slug: "worksome", country: "Global", service: "Contractor Management" },
  { name: "Coupa Contingent Workforce", slug: "coupa-contingent-workforce", country: "Global", service: "Contractor Management" },
  { name: "Sirion", slug: "sirion", country: "Global", service: "Contractor Management" },
  { name: "Gep Smart", slug: "gep-smart", country: "Global", service: "Contractor Management" },
  { name: "Ivalua", slug: "ivalua", country: "Global", service: "Contractor Management" },
  { name: "Sap Ariba", slug: "sap-ariba", country: "Global", service: "Contractor Management" },
  { name: "Jaggaer", slug: "jaggaer", country: "Global", service: "Contractor Management" },
  { name: "Oracle Procurement Cloud", slug: "oracle-procurement-cloud", country: "Global", service: "Contractor Management" },
  { name: "Proactis", slug: "proactis", country: "Global", service: "Contractor Management" },
  { name: "Synertrade", slug: "synertrade", country: "Global", service: "Contractor Management" },
  { name: "Cognilix", slug: "cognilix", country: "Global", service: "Contractor Management" },
  { name: "Zycus", slug: "zycus", country: "Global", service: "Contractor Management" },
  { name: "Volopay", slug: "volopay", country: "Global", service: "Contractor Management" },
  { name: "Tyasuite", slug: "tyasuite", country: "Global", service: "Contractor Management" },
  { name: "Bluesky Medical Staffing Suite", slug: "bluesky-medical-staffing-suite", country: "Global", service: "Contractor Management" },
  { name: "Connecteam", slug: "connecteam", country: "Global", service: "Contractor Management" },
  { name: "Qgenda", slug: "qgenda", country: "Global", service: "Contractor Management" },
  { name: "Vars Health", slug: "vars-health", country: "Global", service: "Contractor Management" },
  { name: "Prosperix", slug: "prosperix", country: "Global", service: "Contractor Management" },
  { name: "Link Squares", slug: "link-squares", country: "Global", service: "Contractor Management" },
  { name: "Compliancequest", slug: "compliancequest", country: "Global", service: "Contractor Management" },
  { name: "Conga Clm", slug: "conga-clm", country: "Global", service: "Contractor Management" },
  { name: "Agiloft", slug: "agiloft", country: "Global", service: "Contractor Management" },
  { name: "Contractworks", slug: "contractworks", country: "Global", service: "Contractor Management" },
  { name: "Contractsafe", slug: "contractsafe", country: "Global", service: "Contractor Management" },
  { name: "Docusign Clm", slug: "docusign-clm", country: "Global", service: "Contractor Management" },
  { name: "Simplify Vms", slug: "simplify-vms", country: "Global", service: "Contractor Management" },
  { name: "PayFit", slug: "payfit", country: "Global", service: "Global Payroll" },
  { name: "ADP TotalSource", slug: "adp-totalsource", country: "Global", service: "EOR, PEO & AOR" },
  { name: "Paychex PEO", slug: "paychex-peo", country: "Global", service: "EOR, PEO & AOR" },
  { name: "CoAdvantage", slug: "coadvantage", country: "Global", service: "EOR, PEO & AOR" },
  { name: "VensureHR", slug: "vensurehr", country: "Global", service: "EOR, PEO & AOR" },
  { name: "Engage PEO", slug: "engage-peo", country: "Global", service: "EOR, PEO & AOR" },
  { name: "BBSI", slug: "bbsi", country: "Global", service: "EOR, PEO & AOR" },
  { name: "Sequoia One", slug: "sequoia-one", country: "Global", service: "EOR, PEO & AOR" },
  { name: "Mercans", slug: "mercans", country: "Global", service: "EOR, PEO & AOR" },
  { name: "Neeyamo", slug: "neeyamo", country: "Global", service: "EOR, PEO & AOR" },
  { name: "Mauve Group", slug: "mauve-group", country: "Global", service: "EOR, PEO & AOR" },
  { name: "People 2.0", slug: "people-2-0", country: "Global", service: "EOR, PEO & AOR" },
  { name: "CXC Global", slug: "cxc-global", country: "Global", service: "EOR, PEO & AOR" },
  { name: "Global Expansion (GX)", slug: "global-expansion", country: "Global", service: "EOR, PEO & AOR" },
  { name: "BambooHR", slug: "bamboohr", country: "Global", service: "HRIS" },
  { name: "HiBob", slug: "hibob", country: "Global", service: "HRIS" },
  { name: "Personio", slug: "personio", country: "Global", service: "HRIS" },
  { name: "Factorial HR", slug: "factorial-hr", country: "Global", service: "HRIS" },
  { name: "Paylocity", slug: "paylocity", country: "Global", service: "HRIS" },
  { name: "Workday HCM", slug: "workday-hcm", country: "Global", service: "HRIS" },
  { name: "UKG Pro", slug: "ukg-pro", country: "Global", service: "HRIS" },
  { name: "SAP SuccessFactors", slug: "sap-successfactors", country: "Global", service: "HRIS" },
  { name: "Oracle Cloud HCM", slug: "oracle-cloud-hcm", country: "Global", service: "HRIS" },
  { name: "Dayforce", slug: "dayforce", country: "Global", service: "HRIS" },
  { name: "Namely", slug: "namely", country: "Global", service: "HRIS" },
  { name: "Employment Hero", slug: "employment-hero", country: "Global", service: "HRIS" },
  { name: "Humi", slug: "humi", country: "Canada", service: "HRIS" },
  { name: "CharlieHR", slug: "charliehr", country: "United Kingdom", service: "HRIS" },
  { name: "Breathe HR", slug: "breathe-hr", country: "Global", service: "HRIS" },
  { name: "Lucca", slug: "lucca", country: "France", service: "HRIS" },
  { name: "Teamtailor", slug: "teamtailor", country: "Global", service: "ATS" },
  { name: "Pinpoint", slug: "pinpoint", country: "Global", service: "ATS" },
  { name: "HarmonyHR", slug: "harmonyhr", country: "Global", service: "HRIS" },
  { name: "Gusto", slug: "gusto", country: "United States", service: "Payroll" },
  { name: "Businessolver", slug: "businessolver", country: "Global", service: "Benefits Administration" },
  { name: "League", slug: "league", country: "Global", service: "Health Benefits" },
  { name: "Forma", slug: "forma", country: "Global", service: "Flexible Benefits" },
  { name: "Carrot Fertility", slug: "carrot-fertility", country: "Global", service: "Family Building Benefits" },
  { name: "Maven Clinic", slug: "maven-clinic", country: "Global", service: "Family Health Telehealth" },
  { name: "Lyra Health", slug: "lyra-health", country: "Global", service: "Mental Health Benefits" },
  { name: "BetterUp", slug: "betterup", country: "Global", service: "Professional Coaching" },
  { name: "Bonusly", slug: "bonusly", country: "Global", service: "Employee Recognition" },
  { name: "Lattice", slug: "lattice", country: "Global", service: "Performance Management" },
  { name: "Culture Amp", slug: "culture-amp", country: "Global", service: "Employee Experience" },
  { name: "15Five", slug: "15five", country: "Global", service: "Performance Management" },
  { name: "Reward Gateway", slug: "reward-gateway", country: "Global", service: "Employee Engagement" },
  { name: "Wellable", slug: "wellable", country: "Global", service: "Corporate Wellness" },
  { name: "Benepass", slug: "benepass", country: "Global", service: "Flexible Benefits" },
  { name: "Leapsome", slug: "leapsome", country: "Global", service: "Performance Management" },
  { name: "Calm Business", slug: "calm-business", country: "Global", service: "Mental Wellness" },
  { name: "VFS Global", slug: "vfs-global", country: "Global", service: "Immigration" },
  { name: "CIBTvisas", slug: "cibtvisas", country: "Global", service: "Immigration" },
  { name: "Atlys", slug: "atlys", country: "Global", service: "Immigration" },
  { name: "iVisa", slug: "ivisa", country: "Global", service: "Immigration" },
  { name: "VisaHQ", slug: "visahq", country: "Global", service: "Immigration" },
  { name: "WWICS Group", slug: "wwics-group", country: "Global", service: "Immigration" },
  { name: "Green and Spiegel", slug: "green-and-spiegel", country: "Global", service: "Immigration" },
  { name: "Siskind Susser PC", slug: "siskind-susser-pc", country: "Global", service: "Immigration" },
  { name: "Murthy Law Firm", slug: "murthy-law-firm", country: "Global", service: "Immigration" },
  { name: "Chugh LLP", slug: "chugh-llp", country: "Global", service: "Immigration" },
  { name: "Vialto Partners", slug: "vialto-partners", country: "Global", service: "Immigration" },
  { name: "Beyond Border Global", slug: "beyond-border-global", country: "Global", service: "Immigration" },
  { name: "Berry Appleman & Leiden (BAL)", slug: "bal", country: "Global", service: "Immigration" },
  { name: "WR Immigration", slug: "wr-immigration", country: "Global", service: "Immigration" },
  { name: "BLS International", slug: "bls-international", country: "Global", service: "Immigration" },
  { name: "Newland Chase", slug: "newland-chase", country: "Global", service: "Immigration" },
  { name: "Alcorn Immigration Law", slug: "alcorn-immigration-law", country: "Global", service: "Immigration" },
  { name: "Klasko Immigration Law Partners", slug: "klasko-immigration-law-partners", country: "Global", service: "Immigration" },
  { name: "Teleport", slug: "teleport", country: "Global", service: "Immigration" },
  { name: "Lawfully", slug: "lawfully", country: "Global", service: "Immigration" },
  { name: "Latitude Law", slug: "latitude-law", country: "Global", service: "Immigration" },
  { name: "Global Mobility Solutions (GMS)", slug: "gms", country: "Global", service: "Immigration" },
  { name: "Migrate World", slug: "migrate-world", country: "Global", service: "Immigration" },
  { name: "Globevisa", slug: "globevisa", country: "Global", service: "Immigration" },
  { name: "Arton Capital", slug: "arton-capital", country: "Global", service: "Immigration" },
  { name: "Henley & Partners", slug: "henley-and-partners", country: "Global", service: "Immigration" },
  { name: "Work Permit Cloud", slug: "work-permit-cloud", country: "Global", service: "Immigration" },
  { name: "Citizen Remote", slug: "citizen-remote", country: "Global", service: "Immigration" },
  { name: "Chen Immigration Law (WeGreened)", slug: "chen-immigration", country: "Global", service: "Immigration" },
  { name: "VisaDB", slug: "visadb", country: "Global", service: "Immigration" },
  { name: "Visa4you", slug: "visa4you", country: "Global", service: "Immigration" },
  { name: "BizFilings", slug: "bizfilings", country: "United States", service: "Incorporation" },
  { name: "CorpNet", slug: "corpnet", country: "United States", service: "Company Formation" },
  { name: "Swyft Filings", slug: "swyft-filings", country: "United States", service: "Business Formation" },
  { name: "Bizee", slug: "bizee", country: "United States", service: "LLC Formation" },
  { name: "Northwest Registered Agent", slug: "northwest-registered-agent", country: "United States", service: "Registered Agent" },
  { name: "Firstbase", slug: "firstbase", country: "Global", service: "Global Incorporation,IT Provisioning,Incorporation" },
  { name: "Clevver", slug: "clevver", country: "Global", service: "Virtual Office" },
  { name: "StartFleet", slug: "startfleet", country: "Global", service: "Incorporation" },
  { name: "MyCompanyWorks", slug: "mycompanyworks", country: "United States", service: "Incorporation" },
  { name: "Harbor Compliance", slug: "harbor-compliance", country: "United States", service: "Compliance" },
  { name: "StartGlobal", slug: "startglobal", country: "Global", service: "Incorporation" },
  { name: "Globalfy", slug: "globalfy", country: "Global", service: "International Expansion" },
  { name: "CSC Global", slug: "csc-global", country: "Global", service: "Entity Management" },
  { name: "CT Corp", slug: "ct-corp", country: "United States", service: "Corporate Compliance" },
  { name: "Cogency Global", slug: "cogency-global", country: "Global", service: "Legal Support" },
  { name: "Harvard Business Services", slug: "harvard-business-services", country: "United States", service: "Delaware Formation" },
  { name: "Inc Authority", slug: "inc-authority", country: "United States", service: "Free Formation" },
  { name: "Tailor Brands", slug: "tailor-brands", country: "United States", service: "Branding & Formation" },
  { name: "Rocket Lawyer", slug: "rocket-lawyer", country: "United States", service: "Legal Subscription" },
  { name: "Active Filings", slug: "active-filings", country: "Global", service: "US Market Entry" },
  { name: "MyCorporation", slug: "mycorporation", country: "United States", service: "Business Maintenance" },
  { name: "Filenow", slug: "filenow", country: "United States", service: "Express Formation" },
  { name: "InCorp Services", slug: "incorp-services", country: "United States", service: "Registered Agent" },
  { name: "Workwize", slug: "workwize", country: "Global", service: "IT Provisioning" },
  { name: "GroWrk", slug: "growrk", country: "Global", service: "IT Provisioning" },
  { name: "Electric.ai", slug: "electric-ai", country: "Global", service: "IT Provisioning" },
  { name: "Allwhere", slug: "allwhere", country: "Global", service: "IT Provisioning" },
  { name: "Unduit", slug: "unduit", country: "Global", service: "IT Provisioning" },
  { name: "quipteams", slug: "quipteams", country: "Global", service: "IT Provisioning" },
  { name: "Esevel", slug: "esevel", country: "Global", service: "IT Provisioning" },
  { name: "Deeploi", slug: "deeploi", country: "Global", service: "IT Provisioning" },
  { name: "Lendis", slug: "lendis", country: "Global", service: "IT Provisioning" },
  { name: "Nuwo", slug: "nuwo", country: "Global", service: "IT Provisioning" },
  { name: "ZenAdmin", slug: "zenadmin", country: "Global", service: "IT Provisioning" },
  { name: "Rayda", slug: "rayda", country: "Global", service: "IT Provisioning" },
  { name: "Retriever", slug: "laptop-retriever", country: "Global", service: "IT Provisioning" },
  { name: "RemoAsset", slug: "remoasset", country: "Global", service: "IT Provisioning" },
  { name: "Teqtivity", slug: "teqtivity", country: "Global", service: "IT Provisioning" },
  { name: "Oomnitza", slug: "oomnitza", country: "Global", service: "IT Provisioning" },
  { name: "Asset Panda", slug: "asset-panda", country: "Global", service: "IT Provisioning" },
  { name: "Sortly", slug: "sortly", country: "Global", service: "IT Provisioning" },
  { name: "Pure Storage", slug: "pure-storage-bmaas", country: "Global", service: "IT Provisioning" },
  { name: "Excotek", slug: "excotek", country: "Global", service: "IT Provisioning" },
  { name: "Structured Technologies", slug: "structured-technologies", country: "Global", service: "IT Provisioning" },
  { name: "Bytes Managed IT", slug: "bytes-managed-it", country: "Global", service: "IT Provisioning" },
  { name: "AlphaNet Solutions", slug: "alphanet-solutions", country: "Global", service: "IT Provisioning" },
  { name: "Geek Force USA", slug: "geek-force-usa", country: "Global", service: "IT Provisioning" },
  { name: "Securis", slug: "securis", country: "Global", service: "IT Provisioning" },
  { name: "Iron Mountain ITAD", slug: "iron-mountain-itad", country: "Global", service: "IT Provisioning" },
  { name: "HOBI International", slug: "hobi-international", country: "Global", service: "IT Provisioning" },
  { name: "DMD Systems Recovery", slug: "dmd-systems", country: "Global", service: "IT Provisioning" },
  { name: "ERI (Electronic Recyclers International)", slug: "eri-recycling", country: "Global", service: "IT Provisioning" },
  { name: "ER2", slug: "er2-disposition", country: "Global", service: "IT Provisioning" },
  { name: "Dynamic Lifecycle Innovations", slug: "dynamic-lifecycle", country: "Global", service: "IT Provisioning" },
  { name: "Cascade Asset Management", slug: "cascade-asset-management", country: "Global", service: "IT Provisioning" },
  { name: "SIMS Lifecycle Services", slug: "sims-lifecycle", country: "Global", service: "IT Provisioning" },
  { name: "SK tes", slug: "sk-tes", country: "Global", service: "IT Provisioning" },
  { name: "Hummingbird International", slug: "hummingbird-international", country: "Global", service: "IT Provisioning" },
  { name: "Guardian Data Destruction", slug: "guardian-data-destruction", country: "Global", service: "IT Provisioning" },
  { name: "Freshservice", slug: "freshservice", country: "Global", service: "IT Provisioning" },
  { name: "ServiceNow ITAM", slug: "servicenow-itam", country: "Global", service: "IT Provisioning" },
  { name: "ManageEngine AssetExplorer", slug: "manageengine-assetexplorer", country: "Global", service: "IT Provisioning" },
  { name: "Spiceworks", slug: "spiceworks-itam", country: "Global", service: "IT Provisioning" },
  { name: "SolarWinds Service Desk", slug: "solarwinds-service-desk", country: "Global", service: "IT Provisioning" },
  { name: "Dotstech (Dots)", slug: "dots-it", country: "Global", service: "IT Provisioning" },
  { name: "Setyl", slug: "setyl", country: "Global", service: "IT Provisioning" },
  { name: "InvGate", slug: "invgate", country: "Global", service: "IT Provisioning" },
  { name: "Eton Venture Services", slug: "etonvs", country: "Global", service: "MSA" },
  { name: "Fultonbridge", slug: "fultonbridge", country: "Global", service: "MSA" },
  { name: "Three Sixty Seven Advisors", slug: "threesixtyseven", country: "Global", service: "MSA" },
  { name: "M+A Squared", slug: "mna2", country: "Global", service: "MSA" },
  { name: "Blackcastle Partners", slug: "blackcastlepartners", country: "Global", service: "MSA" },
  { name: "Carter Morse & Goodrich", slug: "cartermorse", country: "Global", service: "MSA" },
  { name: "MDR & Associates", slug: "mdrma", country: "Global", service: "MSA" },
  { name: "Kratos Capital", slug: "kratoscapital", country: "Global", service: "MSA" },
  { name: "Sun Mergers & Acquisitions", slug: "sunbusinessvaluations", country: "Global", service: "MSA" },
  { name: "Bridgehill Partners", slug: "bridgehillpartners", country: "Global", service: "MSA" },
  { name: "Allenby Capital", slug: "allenbycapital", country: "Global", service: "MSA" },
  { name: "Cavendish", slug: "cavendish", country: "Global", service: "MSA" },
  { name: "Corbett Keeling", slug: "corbettkeeling", country: "Global", service: "MSA" },
  { name: "KBS Corporate", slug: "kbscorporate", country: "Global", service: "MSA" },
  { name: "Evercore", slug: "evercore", country: "Global", service: "MSA" },
  { name: "Lazard", slug: "lazard", country: "Global", service: "MSA" },
  { name: "Rothschild & Co", slug: "rothschild", country: "Global", service: "MSA" },
  { name: "Greenhill & Co", slug: "greenhill", country: "Global", service: "MSA" },
  { name: "Houlihan Lokey", slug: "houlihanlokey", country: "Global", service: "MSA" },
  { name: "Perella Weinberg Partners", slug: "perellaweinberg", country: "Global", service: "MSA" },
  { name: "PJT Partners", slug: "pjtpartners", country: "Global", service: "MSA" },
  { name: "Centerview Partners", slug: "centerview", country: "Global", service: "MSA" },
  { name: "Lincoln International", slug: "lincolninternational", country: "Global", service: "MSA" },
  { name: "Miller Buckfire & Co.", slug: "millerbuckfire", country: "Global", service: "MSA" },
  { name: "Cain Brothers", slug: "cainbrothers", country: "Global", service: "MSA" },
  { name: "Berkery, Noyes & Co.", slug: "berkerynoyes", country: "Global", service: "MSA" },
  { name: "Needham & Co.", slug: "needhamco", country: "Global", service: "MSA" },
  { name: "Cowen", slug: "cowen", country: "Global", service: "MSA" },
  { name: "Allen & Company", slug: "allen-co", country: "Global", service: "MSA" },
  { name: "Oaklins", slug: "oaklins", country: "Global", service: "MSA" },
  { name: "Livingstone Partners", slug: "livingstonepartners", country: "Global", service: "MSA" },
  { name: "Harris Williams", slug: "harriswilliams", country: "Global", service: "MSA" },
  { name: "GCA Altium", slug: "gcaaltium", country: "Global", service: "MSA" },
  { name: "Financo", slug: "financo", country: "Global", service: "MSA" },
  { name: "Marlin & Associates", slug: "marlinassociates", country: "Global", service: "MSA" },
  { name: "Sagent Advisors", slug: "sagentadvisors", country: "Global", service: "MSA" },
  { name: "Diversified Business Advisors", slug: "diversifiedbusiness", country: "Global", service: "MSA" },
  { name: "Moelis & Company", slug: "moelis", country: "Global", service: "MSA" },
  { name: "William Blair", slug: "williamblair", country: "Global", service: "MSA" },
  { name: "Arma Partners", slug: "armapartners", country: "Global", service: "MSA" },
  { name: "Duff & Phelps (Kroll)", slug: "duffandphelps", country: "Global", service: "MSA" },
  { name: "Oppenheimer & Co.", slug: "oppenheimer", country: "Global", service: "MSA" },
  { name: "Jefferies", slug: "jefferies", country: "Global", service: "MSA" },
  { name: "Edelman", slug: "edelman", country: "Global", service: "MARKETING-AGENCY" },
  { name: "BBDO Worldwide", slug: "bbdo", country: "Global", service: "MARKETING-AGENCY" },
  { name: "DDB Worldwide", slug: "ddb", country: "Global", service: "MARKETING-AGENCY" },
  { name: "McCann Worldgroup", slug: "mccann", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Havas Group", slug: "havas", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Leo Burnett", slug: "leoburnett", country: "Global", service: "MARKETING-AGENCY" },
  { name: "TBWA Worldwide", slug: "tbwa", country: "Global", service: "MARKETING-AGENCY" },
  { name: "AKQA", slug: "akqa", country: "Global", service: "MARKETING-AGENCY" },
  { name: "VMLY&R", slug: "vmlyr", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Droga5", slug: "droga5", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Grey Group", slug: "grey", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Golin", slug: "golin", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Weber Shandwick", slug: "webershandwick", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Ketchum", slug: "ketchum", country: "Global", service: "MARKETING-AGENCY" },
  { name: "R/GA", slug: "rga", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Huge", slug: "hugeinc", country: "Global", service: "MARKETING-AGENCY" },
  { name: "72andSunny", slug: "72andsunny", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Razorfish", slug: "razorfish", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Bartle Bogle Hegarty", slug: "bbh", country: "Global", service: "MARKETING-AGENCY" },
  { name: "Adecco", slug: "adecco", country: "Global", service: "Staffing" },
  { name: "ManpowerGroup", slug: "manpowergroup", country: "Global", service: "Staffing" },
  { name: "Robert Half", slug: "robert-half", country: "Global", service: "Staffing" },
  { name: "Hays", slug: "hays", country: "Global", service: "Staffing" },
  { name: "Michael Page", slug: "michael-page", country: "Global", service: "Staffing" },
  { name: "Korn Ferry", slug: "korn-ferry", country: "Global", service: "Staffing" },
  { name: "Kelly Services", slug: "kelly-services", country: "Global", service: "Staffing" },
  { name: "Lupa", slug: "lupa", country: "Global", service: "Staffing" },
  { name: "Hire Overseas", slug: "hire-overseas", country: "Global", service: "Staffing" },
  { name: "Near", slug: "hire-with-near", country: "Global", service: "Staffing" },
  { name: "Hudson", slug: "hudson", country: "Global", service: "Staffing" },
  { name: "Stanton Chase", slug: "stanton-chase", country: "Global", service: "Staffing" },
  { name: "Pedersen & Partners", slug: "pedersen-and-partners", country: "Global", service: "Staffing" },
  { name: "Harvey Nash", slug: "harvey-nash", country: "Global", service: "Staffing" },
  { name: "Floowi", slug: "floowi", country: "Global", service: "Staffing" },
  { name: "GoGloby", slug: "gogloby", country: "Global", service: "Staffing" },
  { name: "ISC Recruitment", slug: "isc-recruitment", country: "Global", service: "Staffing" },
  { name: "NPAworldwide", slug: "npaworldwide", country: "Global", service: "Staffing" },
  { name: "South", slug: "south", country: "Global", service: "Staffing" },
  { name: "NES Fircroft", slug: "nes-fircroft", country: "Global", service: "Staffing" },
  { name: "Spencer Stuart", slug: "spencer-stuart", country: "Global", service: "Staffing" },
  { name: "Insight Global", slug: "insight-global", country: "Global", service: "Staffing" },
  { name: "Aerotek", slug: "aerotek", country: "Global", service: "Staffing" },
  { name: "Kforce", slug: "kforce", country: "Global", service: "Staffing" },
  { name: "Aquent", slug: "aquent", country: "Global", service: "Staffing" },
  { name: "Sage IT", slug: "sage-it", country: "Global", service: "Staffing" },
  { name: "Deloitte", slug: "deloitte", country: "Global", service: "Tax" },
  { name: "PwC", slug: "pwc", country: "Global", service: "Tax" },
  { name: "EY", slug: "ey", country: "Global", service: "Tax" },
  { name: "KPMG", slug: "kpmg", country: "Global", service: "Tax" },
  { name: "Longview Tax", slug: "longview-tax", country: "Global", service: "Tax" },
  { name: "Zoho Books", slug: "zoho-books", country: "Global", service: "Tax" },
  { name: "TaxDome", slug: "taxdome", country: "Global", service: "Tax" },
  { name: "Mango Practice Management", slug: "mango-practice-management", country: "Global", service: "Tax" },
  { name: "Aeco Tax Technology", slug: "aeco-tax-technology", country: "Global", service: "Tax" },
  { name: "ATOM", slug: "atom", country: "Global", service: "Tax" },
  { name: "Avii", slug: "avii", country: "Global", service: "Tax" },
  { name: "Corvee", slug: "corvee-tax-planning", country: "Global", service: "Tax" },
  { name: "Digita", slug: "digita-professional-suite", country: "Global", service: "Tax" },
  { name: "Fyn", slug: "fyn", country: "Global", service: "Tax" },
  { name: "OIC Tax Planner", slug: "oic-tax-planner", country: "Global", service: "Tax" },
  { name: "Once Accounting", slug: "once-accounting", country: "Global", service: "Tax" },
  { name: "SeQwens", slug: "seqwens", country: "Global", service: "Tax" },
  { name: "Taxaroo", slug: "taxaroo", country: "Global", service: "Tax" },
  { name: "Taxfiler", slug: "taxfiler", country: "Global", service: "Tax" },
  { name: "Taxjoy", slug: "taxjoy", country: "Global", service: "Tax" },
  { name: "TaxWorkFlow", slug: "taxworkflow", country: "Global", service: "Tax" },
  { name: "Vertex", slug: "vertex-o-series", country: "Global", service: "Tax" },
  { name: "Thomson Reuters", slug: "thomson-reuters-cs-professional-suite", country: "Global", service: "Tax" },
  { name: "Fonoa", slug: "fonoa", country: "Global", service: "Tax" },
  { name: "Pajakku", slug: "pajakku", country: "Global", service: "Tax" },
  { name: "TaxAct", slug: "taxact-business", country: "Global", service: "Tax" },
  { name: "Quaderno", slug: "quaderno", country: "Global", service: "Tax" },
  { name: "Sovos", slug: "sovos", country: "Global", service: "Tax" },
  { name: "ContractPodAi", slug: "contractpodai", country: "Global", service: "Software" },
  { name: "Blue Marble Global Payroll", slug: "blue-marble-global-payroll", country: "Global", service: "Payroll" },
  { name: "Zoho People", slug: "zoho-people", country: "Global", service: "HRIS" },
  { name: "Visa First", slug: "visa-first", country: "Global", service: "Immigration" },
  { name: "G3 Global Services", slug: "g3-global-services", country: "Global", service: "Immigration" },
  { name: "Relocate.world", slug: "relocate-world", country: "Global", service: "Immigration" },
  { name: "Hofy", slug: "hofy", country: "Global", service: "Software" },
  {name: "worksuite", slug: "worksuite", country: "Global", service: "Contractor Management" },
  { name: "Bolto", slug: "bolto", country: "Global", service: "ai-workforce" },
  { name: "Sparrow Infinity", slug: "sparrow-infinity", country: "Global", service: "industrial-compliance" },
  { name: "Wingspan", slug: "wingspan", country: "Global", service: "freelancer-ops" },
  { name: "Twind (by CTAIMA)", slug: "twind", country: "Global", service: "contractor-management" },
  { name: "Planera", slug: "planera", country: "Global", service: "contractor-management" },
  { name: "Workyard", slug: "workyard", country: "Global", service: "contractor-management" },
  { name: "Shield Geo", slug: "shield-geo", country: "Global", service: "eor-peo-aor" },
  { name: "Panther", slug: "panther", country: "Global", service: "eor-peo-aor" },
  { name: "Asanify", slug: "asanify", country: "Global", service: "eor-peo-aor" },
  { name: "Remunance", slug: "remunance", country: "Global", service: "eor-peo-aor" },
  { name: "PrestigePEO", slug: "prestige-peo", country: "Global", service: "eor-peo-aor" },
  { name: "Transformify", slug: "transformify", country: "Global", service: "eor-peo-aor" },
  { name: "Gibson Watts Global", slug: "gibson-watts", country: "Global", service: "eor-peo-aor" },
  { name: "PayInOne", slug: "payinone", country: "Global", service: "eor-peo-aor" },
  { name: "Helios HR", slug: "helios", country: "Global", service: "eor-peo-aor" },
  { name: "TalentBurst", slug: "talentburst", country: "Global", service: "eor-peo-aor" },
  { name: "Vendorpass", slug: "vendorpass", country: "Global", service: "eor-peo-aor" },
  { name: "Mismo", slug: "mismo", country: "Global", service: "eor-peo-aor" },
  { name: "Express Global Employment", slug: "express-global", country: "Global", service: "eor-peo-aor" },
  { name: "Global Teams", slug: "global-teams", country: "Global", service: "eor-peo-aor" },
  { name: "Talenteer", slug: "talenteer", country: "Global", service: "eor-peo-aor" },
  { name: "InnoSource", slug: "innosource", country: "Global", service: "eor-peo-aor" },
  { name: "Pangea", slug: "pangea", country: "Global", service: "eor-peo-aor" },
  { name: "Bridge Global", slug: "bridge-global", country: "Global", service: "eor-peo-aor" },
  { name: "Amanita HR Services", slug: "amanita-hr", country: "Global", service: "eor-peo-aor" },
  { name: "Skywork", slug: "skywork", country: "Global", service: "eor-peo-aor" },
  { name: "Pento", slug: "pento", country: "Global", service: "global-payroll" },
  { name: "Bitwage", slug: "bitwage", country: "Global", service: "global-payroll" },
  { name: "Symmetrical.ai", slug: "symmetrical-ai", country: "Global", service: "global-payroll" },
  { name: "Payzaar", slug: "payzaar", country: "Global", service: "global-payroll" },
  { name: "Ontop", slug: "ontop", country: "Global", service: "global-payroll" },
  { name: "Cadana", slug: "cadana", country: "Global", service: "global-payroll" },
  { name: "activpayroll", slug: "activpayroll", country: "Global", service: "global-payroll" },
  { name: "Ramco Systems", slug: "ramco-systems", country: "Global", service: "global-payroll" },
  { name: "GreytHR", slug: "greythr", country: "Global", service: "global-payroll" },
  { name: "Zamp", slug: "zamp", country: "Global", service: "global-payroll" },
  { name: "SD Worx", slug: "sd-worx", country: "Global", service: "global-payroll" },
  { name: "Keka", slug: "keka", country: "Global", service: "global-payroll" },
  { name: "Darwinbox", slug: "darwinbox", country: "Global", service: "global-payroll" },
  { name: "Sprout Solutions", slug: "sprout-solutions", country: "Global", service: "global-payroll" },
  { name: "iiPay", slug: "iipay", country: "Global", service: "global-payroll" },
  { name: "Payspace", slug: "payspace", country: "Global", service: "global-payroll" },
  { name: "Wagepoint", slug: "wagepoint", country: "Global", service: "global-payroll" },
  { name: "Knit People", slug: "knit-people", country: "Global", service: "global-payroll" },
  { name: "Rise People", slug: "rise-people", country: "Global", service: "global-payroll" },
  { name: "Collage HR", slug: "collage-hr", country: "Global", service: "global-payroll" },
  { name: "MHR", slug: "mhr", country: "Global", service: "global-payroll" },
  { name: "Zellis", slug: "zellis", country: "Global", service: "global-payroll" },
  { name: "Azets", slug: "azets", country: "Global", service: "global-payroll" },
  { name: "Patriot Payroll", slug: "patriot-payroll", country: "Global", service: "global-payroll" },
  { name: "OnPay", slug: "onpay", country: "Global", service: "global-payroll" },
  { name: "Square Payroll", slug: "square-payroll", country: "Global", service: "global-payroll" },
  { name: "Homebase Payroll", slug: "homebase-payroll", country: "Global", service: "global-payroll" },
  { name: "Zen HR", slug: "zenhr", country: "Global", service: "global-payroll" },
  { name: "Menaitech", slug: "menaitech", country: "Global", service: "global-payroll" },
  { name: "Bayzat", slug: "bayzat", country: "Global", service: "global-payroll" },
  { name: "PalmHR", slug: "palmhr", country: "Global", service: "global-payroll" },
  { name: "Swingvy", slug: "swingvy", country: "Global", service: "global-payroll" },
  { name: "Talenox", slug: "talenox", country: "Global", service: "global-payroll" },
  { name: "HROne", slug: "hrone", country: "Global", service: "global-payroll" },
  { name: "Pocket HRMS", slug: "pockethrms", country: "Global", service: "global-payroll" },
  { name: "sumHR", slug: "sumhr", country: "Global", service: "global-payroll" },
  { name: "Flare HR", slug: "flarehr", country: "Global", service: "global-payroll" },
  { name: "Wave Payroll", slug: "wave-payroll", country: "Global", service: "global-payroll" },
  { name: "Push Operations", slug: "push-operations", country: "Global", service: "global-payroll" },
  { name: "Immedis", slug: "immedis", country: "Global", service: "global-payroll" },
  { name: "Vanta", slug: "vanta", country: "Global", service: "software-technology-solutions" },
  { name: "Drata", slug: "drata", country: "Global", service: "software-technology-solutions" },
  { name: "Kandji", slug: "kandji", country: "Global", service: "software-technology-solutions" },
  { name: "Breezy HR", slug: "breezy-hr", country: "Global", service: "hris-hrms-ats" },
  { name: "Manatal", slug: "manatal", country: "Global", service: "hris-hrms-ats" },
  { name: "Bullhorn", slug: "bullhorn", country: "Global", service: "hris-hrms-ats" },
  { name: "Loxo", slug: "loxo", country: "Global", service: "hris-hrms-ats" },
  { name: "Recruit CRM", slug: "recruit-crm", country: "Global", service: "hris-hrms-ats" },
  { name: "TalentLyft", slug: "talentlyft", country: "Global", service: "hris-hrms-ats" },
  { name: "ClearCompany", slug: "clearcompany", country: "Global", service: "hris-hrms-ats" },
  { name: "JazzHR", slug: "jazzhr", country: "Global", service: "hris-hrms-ats" },
  { name: "Comeet", slug: "comeet", country: "Global", service: "hris-hrms-ats" },
  { name: "Homerun", slug: "homerun", country: "Global", service: "hris-hrms-ats" },
  { name: "Freshteam", slug: "freshteam", country: "Global", service: "hris-hrms-ats" },
  { name: "BizMerlinHR", slug: "bizmerlinhr", country: "Global", service: "hris-hrms-ats" },
  { name: "OrangeHRM", slug: "orangehrm", country: "Global", service: "hris-hrms-ats" },
  { name: "WebHR", slug: "webhr", country: "Global", service: "hris-hrms-ats" },
  { name: "Bitrix24", slug: "bitrix24", country: "Global", service: "hris-hrms-ats" },
  { name: "Zenefits", slug: "zenefits", country: "Global", service: "hris-hrms-ats" },
  { name: "Paycom", slug: "paycom", country: "Global", service: "hris-hrms-ats" },
  { name: "Paycor", slug: "paycor", country: "Global", service: "hris-hrms-ats" },
  { name: "Bambee", slug: "bambee", country: "Global", service: "hris-hrms-ats" },
  { name: "GoCo", slug: "goco", country: "Global", service: "hris-hrms-ats" },
  { name: "Fetcher", slug: "fetcher", country: "Global", service: "hris-hrms-ats" },
  { name: "Hireology", slug: "hireology", country: "Global", service: "hris-hrms-ats" },
  { name: "HiredScore", slug: "hiredscore", country: "Global", service: "hris-hrms-ats" },
  { name: "Eightfold.ai", slug: "eightfold-ai", country: "Global", service: "hris-hrms-ats" },
  { name: "Beamery", slug: "beamery", country: "Global", service: "hris-hrms-ats" },
  { name: "Phenom", slug: "phenom", country: "Global", service: "hris-hrms-ats" },
  { name: "SeekOut", slug: "seekout", country: "Global", service: "hris-hrms-ats" },
  { name: "Entelo", slug: "entelo", country: "Global", service: "hris-hrms-ats" },
  { name: "Textio", slug: "textio", country: "Global", service: "hris-hrms-ats" },
  { name: "TestGorilla", slug: "testgorilla", country: "Global", service: "hris-hrms-ats" },
  { name: "Codility", slug: "codility", country: "Global", service: "hris-hrms-ats" },
  { name: "HackerRank", slug: "hackerrank", country: "Global", service: "hris-hrms-ats" },
  { name: "VidCruiter", slug: "vidcruiter", country: "Global", service: "hris-hrms-ats" },
  { name: "Spark Hire", slug: "spark-hire", country: "Global", service: "hris-hrms-ats" },
  { name: "HireVue", slug: "hirevue", country: "Global", service: "hris-hrms-ats" },
  { name: "Paradox", slug: "paradox", country: "Global", service: "hris-hrms-ats" },
  { name: "Crelate", slug: "crelate", country: "Global", service: "hris-hrms-ats" },
  { name: "TargetRecruit", slug: "targetrecruit", country: "Global", service: "hris-hrms-ats" },
  { name: "AkkenCloud", slug: "akkencloud", country: "Global", service: "hris-hrms-ats" },
  { name: "PageUp", slug: "pageup", country: "Global", service: "hris-hrms-ats" },
  { name: "MokaHR", slug: "mokahr", country: "Global", service: "hris-hrms-ats" },
  { name: "Zelt", slug: "zelt", country: "Global", service: "hris-hrms-ats" },
  { name: "EMP Trust (HireOnboard)", slug: "emp-trust", country: "Global", service: "hris-hrms-ats" },
  { name: "Optimum HRIS", slug: "optimum-hris", country: "Global", service: "hris-hrms-ats" },
  { name: "Sloneek", slug: "sloneek", country: "Global", service: "hris-hrms-ats" },
  { name: "Quikchex", slug: "quikchex", country: "Global", service: "hris-hrms-ats" },
  { name: "HealthJoy", slug: "healthjoy", country: "Global", service: "human-resource-benefits" },
  { name: "Lively", slug: "lively", country: "Global", service: "human-resource-benefits" },
  { name: "HealthEquity", slug: "healthequity", country: "Global", service: "human-resource-benefits" },
  { name: "Benefitfocus", slug: "benefitfocus", country: "Global", service: "human-resource-benefits" },
  { name: "WEX", slug: "wex", country: "Global", service: "human-resource-benefits" },
  { name: "Navia Benefit Solutions", slug: "navia", country: "Global", service: "human-resource-benefits" },
  { name: "Human Interest", slug: "human-interest", country: "Global", service: "human-resource-benefits" },
  { name: "Guideline", slug: "guideline", country: "Global", service: "human-resource-benefits" },
  { name: "ForUsAll", slug: "forusall", country: "Global", service: "human-resource-benefits" },
  { name: "Gradifi (by E*TRADE)", slug: "gradifi", country: "Global", service: "human-resource-benefits" },
  { name: "Goodly", slug: "goodly", country: "Global", service: "human-resource-benefits" },
  { name: "Kindbody", slug: "kindbody", country: "Global", service: "human-resource-benefits" },
  { name: "Progyny", slug: "progyny", country: "Global", service: "human-resource-benefits" },
  { name: "Cleo", slug: "cleo", country: "Global", service: "human-resource-benefits" },
  { name: "Helpr", slug: "helpr", country: "Global", service: "human-resource-benefits" },
  { name: "Bright Horizons", slug: "bright-horizons", country: "Global", service: "human-resource-benefits" },
  { name: "Paytient", slug: "paytient", country: "Global", service: "human-resource-benefits" },
  { name: "First Dollar", slug: "first-dollar", country: "Global", service: "human-resource-benefits" },
  { name: "Fringe", slug: "fringe", country: "Global", service: "human-resource-benefits" },
  { name: "PerkUp", slug: "perkup", country: "Global", service: "human-resource-benefits" },
  { name: "Compt", slug: "compt", country: "Global", service: "human-resource-benefits" },
  { name: "Fond", slug: "fond", country: "Global", service: "human-resource-benefits" },
  { name: "Snappy", slug: "snappy", country: "Global", service: "human-resource-benefits" },
  { name: "Blueboard", slug: "blueboard", country: "Global", service: "human-resource-benefits" },
  { name: "Awardco", slug: "awardco", country: "Global", service: "human-resource-benefits" },
  { name: "Motivosity", slug: "motivosity", country: "Global", service: "human-resource-benefits" },
  { name: "Cooleaf", slug: "cooleaf", country: "Global", service: "human-resource-benefits" },
  { name: "Nectar", slug: "nectar", country: "Global", service: "human-resource-benefits" },
  { name: "Strive Benefits", slug: "strive-benefits", country: "Global", service: "human-resource-benefits" },
  { name: "Hinge Health", slug: "hinge-health", country: "Global", service: "human-resource-benefits" },
  { name: "WellRight", slug: "wellright", country: "Global", service: "human-resource-benefits" },
  { name: "Virgin Pulse", slug: "virgin-pulse", country: "Global", service: "human-resource-benefits" },
  { name: "Omada Health", slug: "omada-health", country: "Global", service: "human-resource-benefits" },
  { name: "Headspace", slug: "headspace", country: "Global", service: "human-resource-benefits" },
  { name: "Spring Health", slug: "spring-health", country: "Global", service: "human-resource-benefits" },
  { name: "Unmind", slug: "unmind", country: "Global", service: "human-resource-benefits" },
  { name: "Pelago", slug: "pelago", country: "Global", service: "human-resource-benefits" },
  { name: "Sword Health", slug: "sword-health", country: "Global", service: "human-resource-benefits" },
  { name: "Kaia Health", slug: "kaia-health", country: "Global", service: "human-resource-benefits" },
  { name: "Origin", slug: "origin", country: "Global", service: "human-resource-benefits" },
  { name: "Northstar", slug: "northstar", country: "Global", service: "human-resource-benefits" },
  { name: "LearnLux", slug: "learnlux", country: "Global", service: "human-resource-benefits" },
  { name: "YourMoneyLine", slug: "yourmoneyline", country: "Global", service: "human-resource-benefits" },
  { name: "Milk Stork", slug: "milk-stork", country: "Global", service: "human-resource-benefits" },
  { name: "UrbanSitter", slug: "urbansitter", country: "Global", service: "human-resource-benefits" },
  { name: "Sittercity", slug: "sittercity", country: "Global", service: "human-resource-benefits" },
  { name: "Care.com", slug: "care-com", country: "Global", service: "human-resource-benefits" },
  { name: "Kinside", slug: "kinside", country: "Global", service: "human-resource-benefits" },
  { name: "WeeCare (now Upwards)", slug: "weecare", country: "Global", service: "human-resource-benefits" },
  { name: "Perkbox", slug: "perkbox", country: "Global", service: "human-resource-benefits" },
  { name: "Empuls", slug: "empuls", country: "Global", service: "human-resource-benefits" },
  { name: "Xoxoday", slug: "xoxoday", country: "Global", service: "human-resource-benefits" },
  { name: "Alma", slug: "alma", country: "Global", service: "immigration-visa" },
  { name: "Imagility", slug: "imagility", country: "Global", service: "immigration-visa" },
  { name: "Docketwise", slug: "docketwise", country: "Global", service: "immigration-visa" },
  { name: "Complize", slug: "complize", country: "Global", service: "immigration-visa" },
  { name: "eIMMIGRATION (by Cerenade)", slug: "eimmigration", country: "Global", service: "immigration-visa" },
  { name: "Lawlogix Edge (by Hyland)", slug: "lawlogix", country: "Global", service: "immigration-visa" },
  { name: "LollyLaw", slug: "lollylaw", country: "Global", service: "immigration-visa" },
  { name: "Filevine", slug: "filevine", country: "Global", service: "immigration-visa" },
  { name: "Neostella", slug: "neostella", country: "Global", service: "immigration-visa" },
  { name: "ImmiCompliance", slug: "immicompliance", country: "Global", service: "immigration-visa" },
  { name: "Flamingo Compliance", slug: "flamingo-compliance", country: "Global", service: "immigration-visa" },
  { name: "BlueDot", slug: "bluedot", country: "Global", service: "immigration-visa" },
  { name: "AbacusLaw", slug: "abacuslaw", country: "Global", service: "immigration-visa" },
  { name: "Countrywide Visas", slug: "countrywide-visas", country: "Global", service: "immigration-visa" },
  { name: "XIPHIAS Immigration", slug: "xiphias", country: "Global", service: "immigration-visa" },
  { name: "World Visa (World Visa Group)", slug: "world-visa", country: "Global", service: "immigration-visa" },
  { name: "VisaPlace", slug: "visaplace", country: "Global", service: "immigration-visa" },
  { name: "Migreat", slug: "migreat", country: "Global", service: "immigration-visa" },
  { name: "Migronis", slug: "migronis", country: "Global", service: "immigration-visa" },
  { name: "CS Global Partners", slug: "csglobal", country: "Global", service: "immigration-visa" },
  { name: "Astons", slug: "astons", country: "Global", service: "immigration-visa" },
  { name: "PassPro", slug: "passpro", country: "Global", service: "immigration-visa" },
  { name: "Harvey Law Group (HLG)", slug: "harvey-law", country: "Global", service: "immigration-visa" },
  { name: "Sable International", slug: "sable-international", country: "Global", service: "immigration-visa" },
  { name: "Smith Stone Walters", slug: "smith-stone-walters", country: "Global", service: "immigration-visa" },
  { name: "DavidsonMorris", slug: "davidsonmorris", country: "Global", service: "immigration-visa" },
  { name: "Westkin Associates", slug: "westkin", country: "Global", service: "immigration-visa" },
  { name: "Reiss Edwards", slug: "reiss-edwards", country: "Global", service: "immigration-visa" },
  { name: "Giambrone & Partners", slug: "giambrone", country: "Global", service: "immigration-visa" },
  { name: "White Rose Visas", slug: "white-rose-visas", country: "Global", service: "immigration-visa" },
  { name: "PassRight", slug: "passright", country: "Global", service: "immigration-visa" },
  { name: "Visas Avenue", slug: "visas-avenue", country: "Global", service: "immigration-visa" },
  { name: "Abhinav Immigration", slug: "abhinav-immigration", country: "Global", service: "immigration-visa" },
  { name: "Kansas Overseas", slug: "kansas-overseas", country: "Global", service: "immigration-visa" },
  { name: "Nationwide Visas", slug: "nationwide-visas", country: "Global", service: "immigration-visa" },
  { name: "Y-Axis", slug: "y-axis", country: "Global", service: "immigration-visa" },
  { name: "Campbell Cohen (CanadaVisa)", slug: "campbell-cohen", country: "Global", service: "immigration-visa" },
  { name: "VisaEnvoy", slug: "visaenvoy", country: "Global", service: "immigration-visa" },
  { name: "Stratix Consultants", slug: "stratix-consultants", country: "Global", service: "immigration-visa" },
  { name: "Syncvisas", slug: "syncvisas", country: "Global", service: "immigration-visa" },
  { name: "First Class Immigration", slug: "first-class-immigration", country: "Global", service: "immigration-visa" },
  { name: "Migra-Code", slug: "migra-code", country: "Global", service: "immigration-visa" },
  { name: "Get Golden Visa", slug: "get-golden-visa", country: "Global", service: "immigration-visa" },
  { name: "La Vida Golden Visas", slug: "la-vida", country: "Global", service: "immigration-visa" },
  { name: "Passportia", slug: "passportia", country: "Global", service: "immigration-visa" },
  { name: "Settle-in", slug: "settle-in", country: "Global", service: "immigration-visa" },
  { name: "Settly", slug: "settly", country: "Global", service: "immigration-visa" },
  { name: "ReloTalent", slug: "relotalent", country: "Global", service: "immigration-visa" },
  { name: "Benivo", slug: "benivo", country: "Global", service: "immigration-visa" },
  { name: "Equus Software", slug: "equus-software", country: "Global", service: "immigration-visa" },
  { name: "SIRVA", slug: "sirva", country: "Global", service: "immigration-visa" },
  { name: "TurboTax", slug: "turbotax", country: "Global", service: "taxation" },
  { name: "H&R Block", slug: "hr-block", country: "Global", service: "taxation" },
  { name: "TaxSlayer", slug: "taxslayer", country: "Global", service: "taxation" },
  { name: "FreeTaxUSA", slug: "freetaxusa", country: "Global", service: "taxation" },
  { name: "Jackson Hewitt", slug: "jackson-hewitt", country: "Global", service: "taxation" },
  { name: "Liberty Tax", slug: "liberty-tax", country: "Global", service: "taxation" },
  { name: "Community Tax", slug: "community-tax", country: "Global", service: "taxation" },
  { name: "Tax Defense Network", slug: "tax-defense-network", country: "Global", service: "taxation" },
  { name: "Tax Guard", slug: "tax-guard", country: "Global", service: "taxation" },
  { name: "Canopy", slug: "canopy", country: "Global", service: "taxation" },
  { name: "Karbon", slug: "karbon", country: "Global", service: "taxation" },
  { name: "TaxCycle", slug: "taxcycle", country: "Global", service: "taxation" },
  { name: "ProConnect", slug: "proconnect", country: "Global", service: "taxation" },
  { name: "Drake Software", slug: "drake-software", country: "Global", service: "taxation" },
  { name: "TaxBit", slug: "taxbit", country: "Global", service: "taxation" },
  { name: "Koinly", slug: "koinly", country: "Global", service: "taxation" },
  { name: "CoinTracker", slug: "cointracker", country: "Global", service: "taxation" },
  { name: "ZenLedger", slug: "zenledger", country: "Global", service: "taxation" },
  { name: "Taxdoo", slug: "taxdoo", country: "Global", service: "taxation" },
  { name: "Hellotax", slug: "hellotax", country: "Global", service: "taxation" },
  { name: "Taxually", slug: "taxually", country: "Global", service: "taxation" },
  { name: "SimplyVAT", slug: "simplyvat", country: "Global", service: "taxation" },
  { name: "VatGlobal", slug: "vatglobal", country: "Global", service: "taxation" },
  { name: "Marosa", slug: "marosa", country: "Global", service: "taxation" },
  { name: "LoVAT", slug: "lovat", country: "Global", service: "taxation" },
  { name: "Taxily", slug: "taxily", country: "Global", service: "taxation" },
  { name: "TaxValet", slug: "taxvalet", country: "Global", service: "taxation" },
  { name: "TaxCloud", slug: "taxcloud", country: "Global", service: "taxation" },
  { name: "Anrok", slug: "anrok", country: "Global", service: "taxation" },
  { name: "Grant Thornton", slug: "grant-thornton", country: "Global", service: "taxation" },
  { name: "SAG Infotech", slug: "sag-infotech", country: "Global", service: "taxation" },
  { name: "ClearTax", slug: "cleartax", country: "Global", service: "taxation" },
  { name: "TaxBuddy", slug: "taxbuddy", country: "Global", service: "taxation" },
  { name: "Quicko", slug: "quicko", country: "Global", service: "taxation" },
  { name: "Boast.ai", slug: "boast-ai", country: "Global", service: "taxation" },
  { name: "Meru Accounting", slug: "meru-accounting", country: "Global", service: "taxation" },
  { name: "CBIZ", slug: "cbiz", country: "Global", service: "taxation" },
  { name: "EisnerAmper", slug: "eisneramper", country: "Global", service: "taxation" },
  { name: "Mazars", slug: "mazars", country: "Global", service: "taxation" },
  { name: "Crowe Global", slug: "crowe", country: "Global", service: "taxation" },
  { name: "Baker Tilly", slug: "baker-tilly", country: "Global", service: "taxation" },
  { name: "Moss Adams", slug: "moss-adams", country: "Global", service: "taxation" },
  { name: "Armanino LLP", slug: "armanino", country: "Global", service: "taxation" },
  { name: "Withum", slug: "withum", country: "Global", service: "taxation" },
  { name: "RubinBrown", slug: "rubinbrown", country: "Global", service: "taxation" },
  { name: "UHY International", slug: "uhy-international", country: "Global", service: "taxation" },
  { name: "Citrin Cooperman", slug: "citrin-cooperman", country: "Global", service: "taxation" },
  { name: "Armanino LLP", slug: "armanino-llp", country: "Global", service: "taxation" },
  { name: "Carr, Riggs & Ingram (CRI)", slug: "carr-riggs-ingram", country: "Global", service: "taxation" },
  { name: "ONESOURCE (by Thomson Reuters)", slug: "onesource", country: "Global", service: "taxation" },
  { name: "TaxPlanner Pro", slug: "taxplanner-pro", country: "Global", service: "taxation" },
  { name: "Holistiplan", slug: "holistiplan", country: "Global", service: "taxation" },
];
